---
- name: Testing andrewrothstein.supervisord
  hosts: all
  tasks:
    - name: Testing andrewrothstein.supervisord (no vars)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Testing andrewrothstein.supervisord (logfile)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
      vars:
        supervisord_addl_settings:
          logfile: /tmp/supervisord-test.log
    - name: Check if additional settings are configured correctly in supervisord.conf
      ansible.builtin.lineinfile:
        path: /etc/supervisor/supervisord.conf
        line: 'logfile=/tmp/supervisord-test.log'
        state: present
      check_mode: true
      register: result
      failed_when: (result is changed) or (result is failed)
